name: deploy website
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Deploy frontend
      #  uses: amondnet/vercel-action@v20
      #  with:
      #    vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #    vercel-args: '--prod' #Optional
      #    vercel-org-id: ${{ secrets.ORG_ID}}  #Required
      #    vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
      #    working-directory: ./frontend

      - name: Git deploy to Heroku
        # You may pin to the exact commit or the version.
        # uses: onekiloparsec/heroku-node-deploy-subfolder@85d5701f800be8126e12b7f6f47e965c71f67b56
        uses: CDNievas/heroku-action@v1.0
        with:
          # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
          api_key: ${{ secrets.HEROKU_TOKEN }}
          # The email of your Heroku account (needed for auth).
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # The app name to use for deploying/updating
          heroku_app_name:  ingalless-website
          # The subfolder where your built code is sitted, e.g. `dist`.
          appdir: strapi
