name: deploy website
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy frontend
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./frontend

      - name: Heroku Action
        uses: CDNievas/heroku-action@v1.0
        with:
          # Used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_TOKEN }}
          # Email from Heroku Account
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # The appname to use for deploying/updating
          heroku_app_name: ingalless-website
          # The branch that you would like to deploy to Heroku
          # branch: # optional, default is HEAD
          # Set this to true if want to use --force
          # useforce: # optional
          # Set if your app is located in a subdirectory.
          appdir: ./strapi 
          # Contents of the Procfile to save and deploy
          # procfile: # optional, default is 
          # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
          # dynamicFiles: # optional
          # Buildpacks to install on Heroku
          # buildpacks: # optional, default is 
          # Path to an localized env file
          # env_file: # optional, default is :  
