name: deploy website
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Deploy frontend
      #  uses: amondnet/vercel-action@v20
      #  with:
      #    vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #    vercel-args: '--prod' #Optional
      #    vercel-org-id: ${{ secrets.ORG_ID}}  #Required
      #    vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
      #    working-directory: ./frontend
      
      - name: Install heroku cli
        run: snap install --classic heroku
      - name: Heroku Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        run: heroku login
      - name: Add remote
        run: heroku git:remote -a ingalless-website  
      - name: Deploy backend to Heroku
        run: git subtree push --prefix strapi heroku main
